/**
 * @license
 * Copyright 2025 Tomny (github.com/VNDT1625/OmniAgent)
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Export the embedded browser's YouTube cookies to a Netscape `cookies.txt`
 * file for yt-dlp (`--cookies <file>`).
 *
 * ## Why
 * yt-dlp's anonymous (logged-out) requests hit YouTube's tiny per-IP quota and
 * get HTTP 429 ("rate-limited") after a few videos, and several caption tracks
 * are gated behind a PO token that only a signed-in session carries. Tomny's
 * embedded browser already runs in the user's REAL persistent session
 * (`session.defaultSession` — see browserViewManager "Session choice"), so the
 * cleanest way past 429 + the caption gate is to hand yt-dlp those very cookies
 * instead of waiting for the rate limit to cool down.
 *
 * ## What
 * Reads the YouTube/Google auth cookies from the given Electron `Session` and
 * writes them in the Netscape cookie-file format yt-dlp expects, into a caller
 * supplied directory (yt-dlp's per-fetch temp dir, deleted afterwards — so the
 * auth cookies never linger on disk).
 *
 * Process boundary: Main-process (Node.js / Electron) module. No DOM APIs. The
 * `Session` is passed in so the whole thing is unit-testable without Electron.
 */

import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';

/** The subset of Electron's `Cookie` we need (kept local so tests need no electron types). */
export type CookieLike = {
  name: string;
  value: string;
  domain?: string;
  path?: string;
  secure?: boolean;
  /** Unix seconds; absent for session cookies. */
  expirationDate?: number;
  hostOnly?: boolean;
};

/** The subset of Electron's `Session.cookies` we use (injectable for tests). */
export type CookieReader = {
  get(filter: { domain?: string }): Promise<CookieLike[]>;
};

/** Domains whose cookies authenticate a YouTube request. */
const YT_COOKIE_DOMAINS = ['.youtube.com', '.google.com'];

/** Escape nothing — Netscape fields are tab-separated; cookie values have no tabs. */
const TRUE_FALSE = (b: boolean): string => (b ? 'TRUE' : 'FALSE');

/**
 * Serialise cookies into Netscape `cookies.txt` format.
 *
 * Format (tab-separated, one cookie per line):
 *   domain  includeSubdomains  path  secure  expiry  name  value
 *
 * yt-dlp also accepts session cookies (expiry 0). The leading
 * `# Netscape HTTP Cookie File` header is required by yt-dlp's parser.
 */
export const toNetscapeCookieFile = (cookies: CookieLike[]): string => {
  const lines = ['# Netscape HTTP Cookie File', '# Generated by Tomny for yt-dlp', ''];
  for (const c of cookies) {
    const domain = c.domain ?? '';
    if (!domain) continue;
    // `hostOnly` cookies must NOT match subdomains; a leading-dot domain does.
    const includeSub = !c.hostOnly && domain.startsWith('.');
    const expiry = c.expirationDate ? Math.floor(c.expirationDate) : 0;
    lines.push(
      [
        domain,
        TRUE_FALSE(includeSub),
        c.path ?? '/',
        TRUE_FALSE(Boolean(c.secure)),
        String(expiry),
        c.name,
        c.value,
      ].join('\t')
    );
  }
  return lines.join('\n') + '\n';
};

/**
 * Read YouTube/Google cookies from `reader` and write a `cookies.txt` into
 * `dir`. Returns the file path, or `null` when there are no usable cookies (so
 * yt-dlp simply runs anonymously). Never throws — a cookie failure must not
 * break transcript extraction.
 *
 * @param reader  Electron `session.cookies` (or a test double).
 * @param dir     Directory to write `cookies.txt` into (yt-dlp's temp dir).
 */
export const writeYoutubeCookieFile = async (reader: CookieReader, dir: string): Promise<string | null> => {
  try {
    const collected: CookieLike[] = [];
    const seen = new Set<string>();
    for (const domain of YT_COOKIE_DOMAINS) {
      const got = await reader.get({ domain }).catch(() => [] as CookieLike[]);
      for (const c of got) {
        // De-dup across the two domain queries (a .google.com cookie can match both).
        const key = `${c.domain}\t${c.path}\t${c.name}`;
        if (seen.has(key)) continue;
        seen.add(key);
        collected.push(c);
      }
    }
    if (collected.length === 0) return null;
    const file = join(dir, 'cookies.txt');
    await writeFile(file, toNetscapeCookieFile(collected), 'utf-8');
    return file;
  } catch {
    return null;
  }
};
