/**
 * @license
 * Copyright 2025 Tomny (github.com/VNDT1625/OmniAgent)
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Localized templates for the IDE Understand feature's DETERMINISTIC fallback
 * summary (the sentence shown for a file the semantic LLM pass never reached).
 *
 * The semantic summaries are generated by the model in the user's display
 * language already; this module keeps the cheap, no-credit fallback summaries in
 * the SAME language so a long-tail file never shows an English sentence inside
 * an otherwise-localized graph. Pure data + tiny formatters — no I/O, no React.
 *
 * Code identifiers (symbol names, file labels) are NEVER translated; only the
 * connective prose is localized. Languages mirror the app's 9 UI locales; an
 * unknown locale falls back to English.
 *
 * Process boundary: shared module (Main builder imports it). No DOM/Node APIs.
 */

import type { ArchLayer } from '@package-apps/ide/process/knowledge/graph/understandTypes';

/** The set of localized strings + formatters needed for one fallback summary. */
export type FallbackStrings = {
  /** Plain role phrase per architectural layer. */
  role: Record<ArchLayer, string>;
  /** Compose the leading clause: `label` is a `lang` file that `role`. */
  base: (label: string, langWord: string, role: string) => string;
  /** Compose the "declares X, Y, Z (+N more)" clause from up-to-3 names + extra. */
  declares: (names: string[], more: number) => string;
  /** Compose the "imported by N files" clause. */
  importedBy: (count: number) => string;
};

/** Normalize an i18n language tag to one of our supported locale keys. */
export const normalizeLocale = (lang: string | undefined): SupportedLocale => {
  if (!lang) return 'en';
  const lower = lang.toLowerCase();
  if (lower.startsWith('vi')) return 'vi';
  if (lower.startsWith('zh')) return lower.includes('tw') || lower.includes('hant') ? 'zh-TW' : 'zh-CN';
  if (lower.startsWith('ja')) return 'ja';
  if (lower.startsWith('ko')) return 'ko';
  if (lower.startsWith('ru')) return 'ru';
  if (lower.startsWith('tr')) return 'tr';
  if (lower.startsWith('uk')) return 'uk';
  return 'en';
};

/** The locale keys this module provides fallback templates for. */
export type SupportedLocale = 'en' | 'vi' | 'zh-CN' | 'zh-TW' | 'ja' | 'ko' | 'ru' | 'tr' | 'uk';

const en: FallbackStrings = {
  role: {
    api: 'exposes an API surface (routes / handlers / endpoints)',
    service: 'holds business logic / service-layer behaviour',
    data: 'defines data models, schema, or persistence access',
    ui: 'renders user interface',
    util: 'provides shared utility / helper functionality',
    config: 'configures the project / build / tooling',
    test: 'contains tests or fixtures',
    unknown: 'is part of the codebase',
  },
  base: (label, langWord, role) => `\`${label}\` is a ${langWord}file that ${role}.`,
  declares: (names, more) =>
    more > 0 ? ` It declares ${names.join(', ')}, and ${more} more.` : ` It declares ${names.join(', ')}.`,
  importedBy: (count) => ` It is imported by ${count} other file${count === 1 ? '' : 's'}.`,
};

const vi: FallbackStrings = {
  role: {
    api: 'cung cấp bề mặt API (route / handler / endpoint)',
    service: 'chứa logic nghiệp vụ / hành vi tầng service',
    data: 'định nghĩa mô hình dữ liệu, schema hoặc truy cập lưu trữ',
    ui: 'kết xuất giao diện người dùng',
    util: 'cung cấp tiện ích / hàm hỗ trợ dùng chung',
    config: 'cấu hình dự án / build / công cụ',
    test: 'chứa test hoặc fixture',
    unknown: 'là một phần của mã nguồn',
  },
  base: (label, langWord, role) => `\`${label}\` là một tệp ${langWord}${role}.`,
  declares: (names, more) =>
    more > 0 ? ` Tệp khai báo ${names.join(', ')} và ${more} ký hiệu khác.` : ` Tệp khai báo ${names.join(', ')}.`,
  importedBy: (count) => ` Được ${count} tệp khác import.`,
};

const zhCN: FallbackStrings = {
  role: {
    api: '暴露 API 接口（路由 / 处理器 / 端点）',
    service: '承载业务逻辑 / 服务层行为',
    data: '定义数据模型、schema 或持久化访问',
    ui: '渲染用户界面',
    util: '提供共享工具 / 辅助功能',
    config: '配置项目 / 构建 / 工具链',
    test: '包含测试或夹具',
    unknown: '是代码库的一部分',
  },
  base: (label, langWord, role) => `\`${label}\` 是一个${langWord}文件，${role}。`,
  declares: (names, more) =>
    more > 0 ? ` 它声明了 ${names.join('、')} 等 ${more + names.length} 个符号。` : ` 它声明了 ${names.join('、')}。`,
  importedBy: (count) => ` 被 ${count} 个其他文件引用。`,
};

const zhTW: FallbackStrings = {
  role: {
    api: '提供 API 介面（路由 / 處理器 / 端點）',
    service: '承載商業邏輯 / 服務層行為',
    data: '定義資料模型、schema 或持久化存取',
    ui: '繪製使用者介面',
    util: '提供共用工具 / 輔助功能',
    config: '設定專案 / 建置 / 工具鏈',
    test: '包含測試或夾具',
    unknown: '是程式碼庫的一部分',
  },
  base: (label, langWord, role) => `\`${label}\` 是一個${langWord}檔案，${role}。`,
  declares: (names, more) =>
    more > 0 ? ` 它宣告了 ${names.join('、')} 等 ${more + names.length} 個符號。` : ` 它宣告了 ${names.join('、')}。`,
  importedBy: (count) => ` 被 ${count} 個其他檔案引用。`,
};

const ja: FallbackStrings = {
  role: {
    api: 'API（ルート / ハンドラー / エンドポイント）を公開する',
    service: 'ビジネスロジック / サービス層の処理を担う',
    data: 'データモデル・スキーマ・永続化アクセスを定義する',
    ui: 'ユーザーインターフェースを描画する',
    util: '共有ユーティリティ / ヘルパー機能を提供する',
    config: 'プロジェクト / ビルド / ツールを設定する',
    test: 'テストやフィクスチャを含む',
    unknown: 'コードベースの一部である',
  },
  base: (label, langWord, role) => `\`${label}\` は${langWord}ファイルで、${role}。`,
  declares: (names, more) =>
    more > 0
      ? ` ${names.join('、')} ほか ${more} 個のシンボルを宣言しています。`
      : ` ${names.join('、')} を宣言しています。`,
  importedBy: (count) => ` 他の ${count} 個のファイルから参照されています。`,
};

const ko: FallbackStrings = {
  role: {
    api: 'API 표면(라우트 / 핸들러 / 엔드포인트)을 노출함',
    service: '비즈니스 로직 / 서비스 계층 동작을 담당함',
    data: '데이터 모델, 스키마 또는 영속화 접근을 정의함',
    ui: '사용자 인터페이스를 렌더링함',
    util: '공용 유틸리티 / 헬퍼 기능을 제공함',
    config: '프로젝트 / 빌드 / 도구를 구성함',
    test: '테스트 또는 픽스처를 포함함',
    unknown: '코드베이스의 일부임',
  },
  base: (label, langWord, role) => `\`${label}\`은(는) ${role} ${langWord}파일입니다.`,
  declares: (names, more) =>
    more > 0 ? ` ${names.join(', ')} 외 ${more}개의 심볼을 선언합니다.` : ` ${names.join(', ')}을(를) 선언합니다.`,
  importedBy: (count) => ` 다른 ${count}개 파일에서 임포트됩니다.`,
};

const ru: FallbackStrings = {
  role: {
    api: 'предоставляет API (маршруты / обработчики / эндпоинты)',
    service: 'содержит бизнес-логику / поведение сервисного слоя',
    data: 'определяет модели данных, схему или доступ к хранилищу',
    ui: 'отрисовывает пользовательский интерфейс',
    util: 'предоставляет общие утилиты / вспомогательные функции',
    config: 'настраивает проект / сборку / инструменты',
    test: 'содержит тесты или фикстуры',
    unknown: 'является частью кодовой базы',
  },
  base: (label, langWord, role) => `\`${label}\` — это ${langWord}файл, который ${role}.`,
  declares: (names, more) =>
    more > 0 ? ` Объявляет ${names.join(', ')} и ещё ${more}.` : ` Объявляет ${names.join(', ')}.`,
  importedBy: (count) => ` Импортируется в ${count} других файлах.`,
};

const tr: FallbackStrings = {
  role: {
    api: 'bir API yüzeyi (rotalar / işleyiciler / uç noktalar) sunar',
    service: 'iş mantığını / servis katmanı davranışını barındırır',
    data: 'veri modellerini, şemayı veya kalıcılık erişimini tanımlar',
    ui: 'kullanıcı arayüzünü oluşturur',
    util: 'paylaşılan yardımcı / araç işlevleri sağlar',
    config: 'projeyi / derlemeyi / araçları yapılandırır',
    test: 'testler veya fikstürler içerir',
    unknown: 'kod tabanının bir parçasıdır',
  },
  base: (label, langWord, role) => `\`${label}\`, ${role} bir ${langWord}dosyadır.`,
  declares: (names, more) =>
    more > 0 ? ` ${names.join(', ')} ve ${more} sembol daha tanımlar.` : ` ${names.join(', ')} tanımlar.`,
  importedBy: (count) => ` ${count} başka dosya tarafından içe aktarılır.`,
};

const uk: FallbackStrings = {
  role: {
    api: 'надає API (маршрути / обробники / точки доступу)',
    service: 'містить бізнес-логіку / поведінку сервісного шару',
    data: 'визначає моделі даних, схему або доступ до сховища',
    ui: 'відмальовує інтерфейс користувача',
    util: 'надає спільні утиліти / допоміжні функції',
    config: 'налаштовує проєкт / збірку / інструменти',
    test: 'містить тести або фікстури',
    unknown: 'є частиною кодової бази',
  },
  base: (label, langWord, role) => `\`${label}\` — це ${langWord}файл, який ${role}.`,
  declares: (names, more) =>
    more > 0 ? ` Оголошує ${names.join(', ')} та ще ${more}.` : ` Оголошує ${names.join(', ')}.`,
  importedBy: (count) => ` Імпортується в ${count} інших файлах.`,
};

/** All locale string tables, keyed by supported locale. */
const TABLES: Record<SupportedLocale, FallbackStrings> = { en, vi, 'zh-CN': zhCN, 'zh-TW': zhTW, ja, ko, ru, tr, uk };

/** Get the fallback string table for a language tag (English when unknown). */
export const fallbackStringsFor = (lang: string | undefined): FallbackStrings => TABLES[normalizeLocale(lang)];

/**
 * The human language NAME (in English) for a BCP-47-ish tag, used to instruct
 * the LLM which language to write its summaries/overview in. Unknown tags
 * default to English.
 */
export const languageNameForPrompt = (lang: string | undefined): string => {
  const names: Record<SupportedLocale, string> = {
    en: 'English',
    vi: 'Vietnamese',
    'zh-CN': 'Simplified Chinese',
    'zh-TW': 'Traditional Chinese',
    ja: 'Japanese',
    ko: 'Korean',
    ru: 'Russian',
    tr: 'Turkish',
    uk: 'Ukrainian',
  };
  return names[normalizeLocale(lang)];
};
